name: yt_main
on: 
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install fonts-ipaexfont    
        pip install --upgrade pip  
        pip install -r requirements.txt

    - name: main
      continue-on-error: true
      run: |
        python ./scripts/main.py
        echo $(TZ=JST-9 date +"%Y/%m/%d %H:%M:%S") | tee GENERATED_DATE.csv
        python ./scripts/visualize_summary_list.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DYN_ACC_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
        AWS_DEFAULT_REGION: "ap-northeast-1"

    - name: upload data
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ./*.png
          ./*.csv
