name: main
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/checkout@v4
    - name: setup
      run: |
        pip install -r requirements.txt

    - name: main
      run: |
        python ./scripts/main.py
